--------------------------------------------------------
-- Archivo creado  - lunes-mayo-08-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CASELLA
--------------------------------------------------------

  CREATE TABLE "OSOLER"."CASELLA" 
   (	"IDSUDOKU" NUMBER(3,0), 
	"COORX" NUMBER(1,0), 
	"COORY" NUMBER(1,0), 
	"VALOR" NUMBER(1,0), 
	"EDITABLE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS" ;
--------------------------------------------------------
--  DDL for Table JUGADOR
--------------------------------------------------------

  CREATE TABLE "OSOLER"."JUGADOR" 
   (	"NOMJUGADOR" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS" ;
--------------------------------------------------------
--  DDL for Table SUDOKU
--------------------------------------------------------

  CREATE TABLE "OSOLER"."SUDOKU" 
   (	"NOMJUGADOR" VARCHAR2(25 BYTE), 
	"IDSUDOKU" NUMBER(3,0), 
	"DATACREACIO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS" ;
--------------------------------------------------------
--  DDL for Index PK_CASELLA
--------------------------------------------------------

  CREATE UNIQUE INDEX "OSOLER"."PK_CASELLA" ON "OSOLER"."CASELLA" ("IDSUDOKU", "COORX", "COORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS" ;
--------------------------------------------------------
--  DDL for Index PERTANYER_FK
--------------------------------------------------------

  CREATE INDEX "OSOLER"."PERTANYER_FK" ON "OSOLER"."CASELLA" ("IDSUDOKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS" ;
--------------------------------------------------------
--  DDL for Index PK_JUGADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "OSOLER"."PK_JUGADOR" ON "OSOLER"."JUGADOR" ("NOMJUGADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS" ;
--------------------------------------------------------
--  DDL for Index PK_SUDOKU
--------------------------------------------------------

  CREATE UNIQUE INDEX "OSOLER"."PK_SUDOKU" ON "OSOLER"."SUDOKU" ("IDSUDOKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS" ;
--------------------------------------------------------
--  DDL for Index TENIR_FK
--------------------------------------------------------

  CREATE INDEX "OSOLER"."TENIR_FK" ON "OSOLER"."SUDOKU" ("NOMJUGADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS" ;
--------------------------------------------------------
--  Constraints for Table CASELLA
--------------------------------------------------------

  ALTER TABLE "OSOLER"."CASELLA" ADD CONSTRAINT "PK_CASELLA" PRIMARY KEY ("IDSUDOKU", "COORX", "COORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS"  ENABLE;
 
  ALTER TABLE "OSOLER"."CASELLA" MODIFY ("IDSUDOKU" NOT NULL ENABLE);
 
  ALTER TABLE "OSOLER"."CASELLA" MODIFY ("COORX" NOT NULL ENABLE);
 
  ALTER TABLE "OSOLER"."CASELLA" MODIFY ("COORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JUGADOR
--------------------------------------------------------

  ALTER TABLE "OSOLER"."JUGADOR" ADD CONSTRAINT "PK_JUGADOR" PRIMARY KEY ("NOMJUGADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS"  ENABLE;
 
  ALTER TABLE "OSOLER"."JUGADOR" MODIFY ("NOMJUGADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUDOKU
--------------------------------------------------------

  ALTER TABLE "OSOLER"."SUDOKU" ADD CONSTRAINT "PK_SUDOKU" PRIMARY KEY ("IDSUDOKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIS"  ENABLE;
 
  ALTER TABLE "OSOLER"."SUDOKU" MODIFY ("NOMJUGADOR" NOT NULL ENABLE);
 
  ALTER TABLE "OSOLER"."SUDOKU" MODIFY ("IDSUDOKU" NOT NULL ENABLE);
